### ISSUE TITLE
Quartus ii 13.1 web edition failed to compile the coding

### ISSUE THREAD

**Issue by zackhaikal** [xesscorp/XuLA#1]
My project aims to use the DE1 SoC FPGA board for obstacle and these are the components used:
i.   ultrasonic sensor
ii.  TRDB LTM LCD
iii. TRDB D5M
when compiling the coding, i got this error
why?
![new issue](https://cloud.githubusercontent.com/assets/17828772/15346846/74a674b4-1cee-11e6-8acb-c1ce98687489.PNG)

**Comment by xesscorp** [comment]
This issue isn't related to the XuLA Board in any way.
